name: Upload Open API to S3 with branch name
on:
  workflow_dispatch:

jobs:
  upload-open-api-to-s3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./design
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: |
          cd ..
          npm install
      - run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: "${{ vars.AWS_REGION }}}}"
      - name: Upload Open API to S3
        run: |
          aws s3 cp ./dist/index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html
