name: Upload Open API to S3 with branch name
on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
    paths:
      - "design/**"
jobs:
  upload-open-api-to-s3:
    uses: ./.github/workflows/upload-open-api.yml
    with:
      s3-upload-path: s3://${{ secrets.S3_BUCKET_NAME }}/${{ github.head_ref }}/index.html
      aws-region: ${{ vars.AWS_REGION }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
